library(Seurat)
library(ggplot2)
library(RColorBrewer)
library(scCustomize)
library(viridis)
library(pheatmap)
library(dplyr)
library(matrixStats)
#---------------------------Figure 1 generate codes---------------------------------------
setwd("/Projects/deng/Rectal/Graph/Part1")
#Rectal.rds was generated by QCAndCellTypeIdentification.code.R
Rectal=readRDS("/Projects/deng/Rectal/Rectal.rds")

#Figure S1B
tiff("clusterLabel.tiff",height=250,width=260)
TSNEPlot(Rectal, label=TRUE,group.by="seurat_clusters",label.size = 6)&NoLegend()&theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
#Figure S1C
Idents(Rectal)=Rectal$seurat_clusters
RectalAveExpr <- AverageExpression(Rectal)[["RNA"]]
pdf("Visualization/RectalClusterRelation.pdf",height=5)
plot(hclust(as.dist(1-cor(RectalAveExpr))),hang=-1)
dev.off()

tiff("sampleLabel.tiff",height=250,width=260)
TSNEPlot(Rectal, group.by="orig.ident")&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()


cellTypeList=c("T cells","Plasma B cells","Naive B cells","Progenitor cell","Macrophages","Neutrophils","Mast cells","Epithelial cells","Endothelial cells","Fibroblasts")
Idents(Rectal)=factor(Idents(Rectal),levels=cellTypeList)
cellTypeColors=c("#6D65BF","#956ED6","#7240E2","#5D477F","#23B0A7","#43B283","#90BA91","#D6A33B","#B58055","#986146")
#Figure 1A
tiff("cellType.tiff",height=250,width=260)
TSNEPlot(Rectal,group.by="cellType",cols=cellTypeColors)&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
pdf("cellType.pdf",height=4,width=4)
TSNEPlot(Rectal,group.by="cellType",cols=cellTypeColors)&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()


#Figure 1B
cellTypeList=c("T cells","Plasma B cells","Naive B cells","Progenitor cell","Macrophages","Neutrophils","Mast cells","Epithelial cells","Endothelial cells","Fibroblasts")
Idents(Rectal)=factor(Idents(Rectal),levels=cellTypeList)
marker=c("CD3D","MZB1","BANK1","MKI67","CD14","G0S2","KIT","CLDN7","SPINK1","ENG","COL3A1");
#marker=c("CD3D","MZB1","CD79A","MS4A1","BANK1","PCLAF","MKI67","CD14","SPP1","S100A9","G0S2","TPSB2","CPA3","TFF3","PHGR1","CLDN5","PLVAP","COL1A1","COL3A1")
cellTypeColors=c("#6D65BF","#956ED6","#7240E2","#5D477F","#23B0A7","#43B283","#90BA91","#D6A33B","#B58055","#986146")
pdf("MarkerVlnPlot.pdf",height=8,width=6)
Stacked_VlnPlot(seurat_object = Rectal,features = rev(marker), plot_spacing = 0,x_lab_rotate =90, colors_use = cellTypeColors)
dev.off()

#Figure 1C
Idents(Rectal)=factor(Idents(Rectal),levels=c("T cells","Plasma B cells","Naive B cells","Progenitor cell","Macrophages","Neutrophils","Mast cells","Epithelial cells","Endothelial cells","Fibroblasts"))
marker=c("CD3D","MZB1","BANK1","MKI67","CD14","G0S2","KIT","CLDN7","SPINK1","ENG","COL3A1");
pal <- viridis(n = 10, option = "D")
tiff("MarkerFeatures.tiff",height=600,width=800)
Plot_Density_Custom(seurat_object = Rectal, features = marker, custom_palette = pal)&NoLegend()&
theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank())&
theme(panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
pdf("MarkerFeaturesForLegend.pdf",height=4,width=5)
Plot_Density_Custom(seurat_object = Rectal, features = c("CDKN1A"), custom_palette = pal)
dev.off()

#Figure 1D
pdf("GroupLabel.pdf",height=7,width=7)
TSNEPlot(Rectal, split.by="group",cols = cellTypeColors,ncol=2)&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", linewidth=1.5, linetype="solid"))
dev.off()

#Figure 1E
Rectal$orig.ident=factor(Rectal$orig.ident,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
cbbPalette <- c("MediumTurquoise", " MediumAquamarine", "Turquoise", "LightSeaGreen", "MediumPurple", "BlueViolet", "Violet", "Magenta")
tiff("sampleLabel.tiff",height=250,width=260)
TSNEPlot(Rectal, group.by="orig.ident",cols=cbbPalette)&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

number=data.frame(n=table(Idents(Rectal)))
number$tmp=1000
pdf("Number.pdf",height=3,width=1)
pheatmap(number[,c(2,3)],cluster_row=F,cluster_col=F,display_numbers = T,number_format="%d",color = colorRampPalette(c("white","Bisque","Coral","OrangeRed","Red"))(50),legend=F)
dev.off()

#Figure 1F
cellTypeList=c("T cells","Plasma B cells","Naive B cells","Progenitor cell","Macrophages","Neutrophils","Mast cells","Epithelial cells","Endothelial cells","Fibroblasts")
t=data.frame(table(Rectal$orig.ident,Rectal$cellType))
total=data.frame(table(Rectal$orig.ident))
result=merge(t,total,by="Var1")
colnames(result)=c("Sample","CellType","TypeNumber","TotalNumber")
result$Ratio=result$TypeNumber/result$TotalNumber
cbbPalette <- c("MediumTurquoise", " MediumAquamarine", "Turquoise", "LightSeaGreen", "MediumPurple", "BlueViolet", "Violet", "Magenta")
Sample_order=factor(result$Sample,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
CellType_order=factor(result$CellType,levels=cellTypeList)
g=ggplot(result, aes(CellType_order, Ratio, fill=Sample_order)) +
  geom_bar(stat="identity",position="fill") +
  scale_y_continuous(expand=c(0,0))+
  theme(axis.text.x = element_text(angle = 0))+
  scale_fill_manual(values=cbbPalette) +
  theme(axis.title.x = element_blank(),axis.text.x = element_text(size=rel(1.0),angle=90,vjust = 0.5, hjust=1))
pdf("cellTypeDistribution8Sample.pdf",height=3,width=4)
print(g)
dev.off()

#Figure 1G
#AllDeGene was generated by D:\Application\Rectal\scripts\DEGAnalysisBetweenConditionInEachCellType.code.R, and then combine then together as AllDeGene
allDeg=read.table("D:/Application/Rectal/DEG/AllDeGene.txt",sep="\t",header=T)
tmp=paste0(allDeg$Group,"_",allDeg$cellType,"_",allDeg$Pattern,sep="")
tmp=as.matrix(table(tmp))
TmpInfo=as.matrix(do.call(rbind, strsplit(as.character(rownames(tmp)),'_')))
result=data.frame("Group"=TmpInfo[,1],"CellType"=TmpInfo[,2],"Pattern"=TmpInfo[,3],"Number"=tmp[,1])
result=result[order(result$Number),]
Sample_order=factor(result$Sample,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
#CellType_order=factor(result$CellType,levels=rev(c("T cells","Epithelial cells","Plasma B cells","Macrophages","B cells","Premature B cell","Fibroblasts","Endothelial cells","Neutrophils","Progenitor cell","Mast cells")))
CellType_order=factor(result$CellType,levels=rev(unique(result$CellType)))
g=ggplot(result, aes(CellType_order, Number, fill=Pattern)) +
  geom_bar(stat="identity") + 
  scale_fill_manual(values=c("lightblue","orange")) +
  scale_y_continuous(expand=c(0,0))+theme_bw()+
  theme(axis.text.x = element_text(angle = 90),axis.title.y = element_blank())+
  theme(axis.title.x = element_blank())+facet_grid(cols = vars(Group))
pdf("DEGdistribution.pdf",height=4,width=8)
print(g)
dev.off()


#Figure 1G
setwd("D:/Application/Rectal/Manuscript/Graph/Part1/")
DEGStatistic=read.table("D:/Application/Rectal/DEG/DEGStatistic.txt",header=T,row.names=1,"\t")
DEGStatistic=DEGStatistic[cellTypeList,]
pdf("DownDEG.pdf",height=4,width=3)
pheatmap(DEGStatistic[,c(5,6,7,8)],cluster_row=F,cluster_col=F,display_numbers = T,number_format="%d",color = colorRampPalette(c("white","LightGreen", "Green"))(50),legend=F)
dev.off()
pdf("UpDEG.pdf",height=4,width=3)
pheatmap(DEGStatistic[,c(1,2,3,4)],cluster_row=F,cluster_col=F,display_numbers = T,number_format="%d",color = colorRampPalette(c("white","Bisque","Coral","OrangeRed","Red"))(50),legend=F)
dev.off()

Pvalue=matrix(data = NA, nrow = dim(DEGStatistic)[1], ncol = 2, byrow = FALSE,dimnames = NULL)
for(i in 1:dim(DEGStatistic)[1]){
  Pvalue[i,1]=phyper(DEGStatistic[i,7]-1,DEGStatistic[i,5],16334-DEGStatistic[i,5],DEGStatistic[i,6],lower.tail = FALSE)
  Pvalue[i,2]=phyper(DEGStatistic[i,3]-1,DEGStatistic[i,1],16334-DEGStatistic[i,1],DEGStatistic[i,2],lower.tail = FALSE)
}
colnames(Pvalue)=c("DnPval","UpPval")
DEGStatisticDf=cbind(DEGStatistic,Pvalue)

DEGStatisticDf$upSig=ifelse(DEGStatisticDf$UpPval<0.01,"Sig","NoSig")
DEGStatisticDf$cellType=factor(rownames(DEGStatisticDf),levels=rev(cellTypeList))
t=ggplot(DEGStatisticDf, aes(cellType, y=-log10(UpPval),fill=upSig))+
geom_bar(stat = "identity",width=0.7)+labs(title="",x="", y = "")+ theme_bw()+coord_flip()+
scale_fill_manual(values=c("LightGrey","red"))+
theme(legend.position="none")+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank())+
theme(axis.title.y = element_text(size=rel(1.0)),axis.text.x = element_text(size=rel(1.0)),axis.text.y = element_text(size=rel(1.0)))
pdf("UpDEGPvalue.pdf",height=3,width=2)
print(t)
dev.off()

DEGStatisticDf$dnSig=ifelse(DEGStatisticDf$DnPval<0.01,"Sig","NoSig")
t=ggplot(DEGStatisticDf, aes(cellType, y=-log10(DnPval),fill=dnSig))+
geom_bar(stat = "identity",width=0.7)+labs(title="",x="", y = "")+ theme_bw()+coord_flip()+
scale_fill_manual(values=c("LightGrey","green"))+
theme(legend.position="none")+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank())+
theme(axis.title.y = element_text(size=rel(1.0)),axis.text.x = element_text(size=rel(1.0)),axis.text.y = element_text(size=rel(1.0)))
pdf("DownDEGPvalue.pdf",height=3,width=2)
print(t)
dev.off()

#data for Figure 1H
EPCBulkDEG=allDeg[allDeg$Group %in% c("PC","SC") & allDeg$cellType%in%"Epithelial cells" & allDeg$Pattern %in% "Up",]
EPCBulkDEGList=split(EPCBulkDEG$Gene,EPCBulkDEG$Group)
EPCBulkDEGList=rbind(toString(EPCBulkDEGList$PC)[1],toString(EPCBulkDEGList$SC))
rownames(EPCBulkDEGList)=c("UpInPC","UpInSC")
write.table(EPCBulkDEGList,file="EPCBulkDEG_metascape.txt",col.names=F,sep="\t",quote=F)


#---------------------------Figure 2 generate codes---------------------------------------
#---------------------------Part 2---------------------------------------
setwd("/Projects/deng/Rectal/Graph/Part2")
EPC=readRDS("/Projects/deng/Rectal/EPC.rds")
#Figure 2A
mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(length(unique(EPC$seurat_clusters)))
pdf("EPCClusterLabel.pdf",height=4,width=4.5)
TSNEPlot(EPC, label=TRUE,cols=mycolors)&NoLegend()&theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
tiff("EPCSampleLabel.tiff",height=250,width=260)
TSNEPlot(EPC, group.by="orig.ident")&NoLegend()&theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
tiff("EPCGroupLabel.tiff",height=250,width=260)
TSNEPlot(EPC, group.by="group",cols = c("LightSkyBlue","MediumPurple","Magenta"))&NoLegend()&theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

#Figure 2B
EPC=subset(EPC,idents=c(0:17))
t=as.matrix(table(EPC$seurat_clusters))
tmp=paste0(EPC$orig.ident,"_",EPC$seurat_clusters,sep="")
tmp=as.matrix(table(tmp))
TmpInfo=as.matrix(do.call(rbind, strsplit(as.character(rownames(tmp)),'_')))
result=data.frame("Sample"=TmpInfo[,1],"CellClusters"=TmpInfo[,2],"Percent"=tmp[,1])
Cluster_order=factor(result$CellClusters,levels=c(17,2,8,6,11,16,15,1,7,12,3,14,9,13,4,5,0,10))
Sample_order=factor(result$Sample,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
cbbPalette <- c("MediumTurquoise", " MediumAquamarine", "Turquoise", "LightSeaGreen", "MediumPurple", "BlueViolet", "Violet", "Magenta")
g=ggplot(result, aes(Cluster_order, Percent, fill=Sample_order)) +
  geom_bar(stat="identity",position="fill") +
  scale_y_continuous(expand=c(0,0))+
  scale_fill_manual(values=cbbPalette)+
  theme(axis.text.x = element_text(angle = 0))+
  theme(axis.title.x = element_blank())
pdf("EPCSampleDis.pdf",width=14,height=5)
print(g)
dev.off()

#Figure 2C was generated using InferCNV

#Figure 2D, regulonActivity_byCellType file was generated by TranscriptionFactorBySCENIC.code.R
TFScore=read.table("D:/Application/Rectal/SCENIC/regulonActivity_byCellType.txt",header=T,row.names=1,sep="\t",check.names=F)
TFScore=TFScore[rowMax(TFScore)>0.01,]
pdf("D:/Application/Rectal/Manuscript/Graph/Part2/heatmapDetail.pdf",height=19)
pheatmap(TFScore,scale="row",clustering_method="ward.D2",color = viridis(10),show_rownames = T)
dev.off()
pdf("D:/Application/Rectal/Manuscript/Graph/Part2/heatmap4TF.pdf",height=6,width=5)
pheatmap(TFScore,scale="row",clustering_method="ward.D2",color = viridis(10),show_rownames = F,border=F)
dev.off()

#target expression of Myc: not show 
exprMatTmp=read.table("D:/Application/Rectal/SCENIC/MYCtarget.txt",header=T,row.names=1,check.names=F)
pdf("D:/Application/Rectal/Manuscript/Graph/Part2/MYCTargetExpr.pdf",height=4,width=5)
pheatmap(exprMatTmp ,scale="row",clustering_method="ward.D2",color = colorRampPalette(c( "navy","white","red"))(50),show_rownames = F)
dev.off()

#Figure 2E
pdf("/Projects/deng/Rectal/Graph/Part2/MYCExpr.pdf",height=2,width=8)
VlnPlot(EPC,features=c("MYC"),pt.size=0)&NoLegend()&
theme(plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

gene=bitr(rownames(exprMatTmp),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]
Function=enrichPathway(gene)
barplot(Function)

#Figure 2G
C0DEG=FindMarkers(EPC,ident.1=c(0),ident.2=c(17,2,8,6,11,16,15),pct.min=0.25)
C0DEG=C0DEG[C0DEG$p_val_adj<0.01,]
C0High=C0DEG[C0DEG$avg_log2FC>1,]
C0Low=C0DEG[C0DEG$avg_log2FC<-1,]
C0HighId=bitr(rownames(C0High),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]
C0LowId=bitr(rownames(C0Low),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]

C10DEG=FindMarkers(EPC,ident.1=c(10),ident.2=c(17,2,8,6,11,16,15),pct.min=0.25)
C10DEG=C10DEG[C10DEG$p_val_adj<0.01,]
C10High=C10DEG[C10DEG$avg_log2FC>1,]
C10Low=C10DEG[C10DEG$avg_log2FC<-1,]
C10HighId=bitr(rownames(C10High),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]
C10LowId=bitr(rownames(C10Low),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]

C13DEG=FindMarkers(EPC,ident.1=13,ident.2=c(17,2,8,6,11,16,15),pct.min=0.25)
C13DEG=C13DEG[C13DEG$p_val_adj<0.01,]
C13High=C13DEG[C13DEG$avg_log2FC>1,]
C13Low=C13DEG[C13DEG$avg_log2FC<-1,]
C13HighId=bitr(rownames(C13High),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]
C13LowId=bitr(rownames(C13Low),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]

C3DEG=FindMarkers(EPC,ident.1=3,ident.2=c(17,2,8,6,11,16,15),pct.min=0.25)
C3DEG=C3DEG[C3DEG$p_val_adj<0.01,]
C3High=C3DEG[C3DEG$avg_log2FC>1,]
C3Low=C3DEG[C3DEG$avg_log2FC<-1,]
C3HighId=bitr(rownames(C3High),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]
C3LowId=bitr(rownames(C3Low),"SYMBOL","ENTREZID",OrgDb="org.Hs.eg.db")[,2]

upDEGId=list("C0High"=C0HighId,"C10High"=C10HighId,"C13High"=C13HighId,"C3High"=C3HighId)
library(UpSetR)
pdf("upDEGOverlap.pdf")
upset(fromList(upDEGId))
dev.off()

upDEGIdGO <- compareCluster(geneCluster = upDEGId, fun = "enrichGO",OrgDb="org.Hs.eg.db",minGSSize = 5,ont="BP")
bp2 <- simplify(upDEGIdGO, cutoff=0.7, by="p.adjust", select_fun=min)
pdf("CancerCellUpGOBPbp2.pdf",width=10,height=5)
dotplot(bp2,showCategory=5,label_format=100)
dev.off()

#---------------------------Figure 3 generate codes---------------------------------------
#---------------------------Part 3 The immune milieu of Rectal---------------------------------------
setwd("/Projects/deng/Rectal/Graph/Part3")
allDeg=read.table("D:/Application/Rectal/DEG/AllDeGene.txt",sep="\t",header=T)
allDeg=allDeg[allDeg$cellType %in% c("T cells","Macrophages","B cells","Mast cells"),]
allDegUp=allDeg[allDeg$Pattern %in% "Up",]
allDegUp=allDeg[allDeg$Group %in% c("SC","PC"),]
allDegUp$Group=paste0(allDegUp$Group,"_",allDegUp$cellType,sep="")
upDEGIdInImmune=split(allDegUp$Gene,allDegUp$Group)
upDEGIdInImmuneGO <- compareCluster(geneCluster = upDEGIdInImmune, fun = "enrichGO",keyType = "SYMBOL",OrgDb="org.Hs.eg.db",minGSSize = 5,ont="BP")
bp2 <- simplify(upDEGIdInImmuneGO, cutoff=0.7, by="p.adjust", select_fun=min)
dotplot(bp2 ,showCategory=10)

#Figure 3A
Tcell=readRDS("/Projects/deng/Rectal/Tcell.rds")
tiff("clusterLabelR0.5.tiff",height=250,width=260)
TSNEPlot(Tcell, label=TRUE,group.by="seurat_clusters",label.size = 6)&NoLegend()&theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
tiff("sampleLabel.tiff",height=250,width=260)
TSNEPlot(Tcell, group.by="orig.ident")&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
tiff("GroupLabel.tiff",height=250,width=260)
TSNEPlot(Tcell, group.by="group",cols = c("LightSkyBlue","DarkViolet","Magenta"))&NoLegend()&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
tiff("cellType.label.tiff",height=250,width=360)
TSNEPlot(Tcell)&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),plot.title=element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
tiff("GroupLabelSplit.tiff",height=310,width=900)
TSNEPlot(Tcell, split.by="group",label=TRUE,label.size = 6)&NoLegend()&theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

tiff("cellType.marker.tiff",width=600)
FeaturePlot(Tcell,features=c("IL7R","CXCL13","FOXP3","CTLA4","IL2RA","CCR7","IL17A","GZMB","GZMK","CRTAM","TRDC","KLRC1","XCL1","FCGR3A"))&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
#https://www.nature.com/articles/s41588-021-00911-1#Sec39

marker4Tcell=c("IL7R","CXCL13","FOXP3","IL2RA","CTLA4","CCR7","IL17A","GZMB","GZMK","CRTAM","TRDC","KLRC1","XCL1","FCGR3A")
t=DotPlot(Tcell,features=marker4Tcell)
g=ggplot(t$data, aes(factor(features.plot,levels=unique(features.plot)), factor(id,levels=rev(c(1,12,13,3,4,15,9,5,7,2,0,6,8,10,11,14))), size= pct.exp,color=avg.exp.scaled)) +geom_point()+
scale_colour_viridis_c()+
labs(color="Average Expression",size="Percent expressed",x="",y="",title="")+
theme_bw()+theme(title = element_text(size=rel(1.0),face="bold"),axis.text.x = element_text(size=rel(1.5),face="bold",angle=90),axis.text.y = element_text(size=rel(1.0),face="bold")) 
pdf("cellType.marker.dotplot.pdf")
print(g)
dev.off()

tiff("cellType.marker.tiff",width=600)
FeaturePlot(Tcell,features=marker4Tcell)&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

IL7R: 1,12,13, CD4, type 1 helper T (TH1) CD4 effector memory T (TEM) cluster :
CXCL13: 3, CD4, follicular helper T (TFH) cells
FOXP3,CTLA4,CD25: 4,9,15, CD4, CD4 clusters consisted of FOXP3+ regulatory T (Treg) 
CCR7: 5, CD4, naive/central memory CD4+ . TCM cells express CD62L (also known as L-selectin) and CC-chemokine receptor 7 (CCR7), circulate in lymphoid organs and have the stem cell-like ability to differentiate and proliferate after receiving proper signals (from antigens or cytokines). 
IL17A:7, CD4, T helper (Th) cells 
GZMB: 2, CD8, effector memory T cells
GZMK: 0, CD8, effector memory T cells
CRTAM:6, CD8,Natural killer T (NKT) cell
TRDC:8,CD8,Natural killer T (NKT) cell
KLRC1:10, CD8,Natural killer cell 
XCL1:11, CD8,Natural killer cell 
FCGR3A:14 CD8,natural killer T (NKT)-like cells: 

tiff("cellType.marker.test.tiff")
FeaturePlot(Tcell,features=c("TNFRSF4"))&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

tiff("Ligand.marker.test.tiff")
FeaturePlot(Rectal,features=c("CD80","CD86","HSP90AA1","TXNIP"))&theme(axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

#Figure 3D
library(ggpubr)
marker=read.table("D:/Application/Rectal/Manuscript/Graph/Part3/validation.txt",header=T)
t=ggplot(marker, aes(x=group, y=CXCL13, color=group))+
geom_boxplot()+labs(title="",x="", y = "")+ 
theme (strip.text= element_text(size=10,face="bold")) + 
stat_compare_means(method = "t.test")+
scale_color_manual(values = c("MediumPurple","Magenta"))+
theme(legend.position="none")+ geom_jitter(position=position_jitter(0.2),size=3)+theme_bw()+
theme(axis.title.y = element_text(size=rel(1.5)),axis.text.x = element_text(size=rel(1.0)),axis.text.y = element_text(size=rel(1.0)))
pdf("D:/Application/Rectal/Manuscript/Graph/Part3/CXCL13.pdf",width=4,height=4)
print(t)
dev.off()
t=ggplot(marker, aes(x=group, y=CTLA4, color=group))+
geom_boxplot()+labs(title="",x="", y = "")+ 
theme (strip.text= element_text(size=10,face="bold")) + 
stat_compare_means(method = "t.test")+
scale_color_manual(values = c("MediumPurple","Magenta"))+
theme(legend.position="none")+ geom_jitter(position=position_jitter(0.2),size=3)+theme_bw()+
theme(axis.title.y = element_text(size=rel(1.5)),axis.text.x = element_text(size=rel(1.0)),axis.text.y = element_text(size=rel(1.0)))
pdf("D:/Application/Rectal/Manuscript/Graph/Part3/CTLA4.pdf",width=4,height=4)
print(t)
dev.off()


#Figure 3B
tmp=paste0(Tcell$group,"_",Tcell$seurat_clusters,sep="")
tmp=as.matrix(table(tmp))
TmpInfo=as.matrix(do.call(rbind, strsplit(as.character(rownames(tmp)),'_')))
result=data.frame("Group"=TmpInfo[,1],"Cluster"=TmpInfo[,2],"Count"=tmp[,1])
groupCount=data.frame(table(Tcell$seurat_clusters))
colnames(groupCount)=c("Cluster","GroupCount")
result=merge(result,groupCount,by="Cluster")
result$Ratio=result$Count/result$GroupCount
Ctrl=result[result$Group %in% "SC",]
Ctrl=Ctrl[order(Ctrl$Ratio),]

tmp=paste0(Tcell$orig.ident,"_",Tcell$seurat_clusters,sep="")
tmp=as.matrix(table(tmp))
TmpInfo=as.matrix(do.call(rbind, strsplit(as.character(rownames(tmp)),'_')))
result=data.frame("Sample"=TmpInfo[,1],"CellClusters"=TmpInfo[,2],"Percent"=tmp[,1])
Cluster_order=factor(result$CellClusters,levels=Ctrl$Cluster)
Sample_order=factor(result$Sample,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
cbbPalette <- c("MediumTurquoise", " MediumAquamarine", "Turquoise", "LightSeaGreen", "MediumPurple", "BlueViolet", "Violet", "Magenta")
g=ggplot(result, aes(Cluster_order, Percent, fill=Sample_order)) +
  geom_bar(stat="identity",position="fill") +
  scale_y_continuous(expand=c(0,0))+theme_bw()+
  scale_fill_manual(values=cbbPalette)+
  theme(axis.text.x = element_text(angle = 0))+
  theme(axis.title.x = element_blank())
pdf("TcellSampleDis.pdf",width=10,height=5)
print(g)
dev.off()


tiff("MarkerFeatures.tiff",height=300,width=1200)
FeaturePlot(Tcell,c("IL17A","CXCL13","GZMK","CTLA4"),pt.size=0.3,ncol=4, cols = c("LightGrey",viridis(10)))&NoLegend()&
theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank())&
theme(panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()


pdf("MarkerFeatures.pdf",height=3)
FeaturePlot(Tcell,c("IL17A","CXCL13","GZMK","CTLA4"),pt.size=0.3,ncol=3, raster=TRUE,cols = c("LightGrey",viridis(10)))&
theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank())&
theme(panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()


tiff("PD1.tiff",height=300,width=600)
FeaturePlot(Tcell,c("CD28","PDCD1","CTLA4"),pt.size=0.3,cols = c("LightGrey",viridis(10)))&NoLegend()&
theme(plot.title=element_blank(),axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank())&
theme(panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

#Figure 3G
data=read.table("D:/Application/Rectal/PairDEG/Tcell/Combine.txt",header=T,row.names=1)
DEGNumber=data.frame(colSums(data != 0))
colnames(DEGNumber)=c("Number")
GeneCount=rowSums(data != 0)
gene=names(GeneCount[GeneCount>2])
data=data[gene,]
rowNumber=rowSums(data!=0)
rowNumber=sort(rowNumber,decreasing=T)
rowName=names(rowNumber)
colNumber=colSums(data!=0)
colNumberSC=colNumber[1:16]
colNumberSC=sort(colNumberSC,decreasing=T)
colNameSC=names(colNumberSC)
colNumberPC=colNumber[17:32]
colNumberPC=sort(colNumberPC,decreasing=T)
colNamePC=names(colNumberPC)
colName=c(colNameSC,colNamePC)
dataOrder=data[rowName,colName]

pdf("D:/Application/Rectal/Manuscript/Graph/Part3/TcellDeg.pdf",width=6,height=6)
pheatmap(t(dataOrder),cluster_row=F,cluster_col=F,show_colnames=T,gaps_row = c(16),color = colorRampPalette(c( "navy","white","firebrick3"))(50),border_color = "white")
dev.off()

DEGNumber$sample=rownames(DEGNumber)
DEGNumber=DEGNumber[colName,]
DEGNumber$Group=c(rep("SC",16),rep("PC",16))
g=ggplot(DEGNumber, aes(factor(sample,levels=rev(sample)), Number, fill=Group)) +
  geom_bar(stat="identity") + coord_flip()+
  scale_y_continuous(expand=c(0,0))+theme_bw()+
  scale_fill_manual(values=c("DarkViolet","Magenta"))+
  theme(axis.text.x = element_text(angle = 0))+
  theme(axis.title.x = element_blank(),axis.title.y = element_blank())
pdf("D:/Application/Rectal/Manuscript/Graph/Part3/DEGNumber4Sample.pdf",width=3,height=6)
print(g)
dev.off()


Idents(Tcell)=Tcell$seurat_clusters
pdf("topDEG.pdf",width=9)
VlnPlot(Tcell,c("HSP90AA1","B2M","HSPA1B","JUN","HSPA1A"),ncol=1,split.by="group",cols = c("LightSkyBlue","MediumPurple","Magenta"),pt.size=0)&NoLegend()&theme(plot.title=element_text(size=10),axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text.x = element_blank(),,panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid")) 
dev.off()

SC3DEG=read.table("D:/Application/Rectal/PairDEG/Tcell/SCGroup/3Deg.txt",header=T)
DegGOBP <- enrichGO(rownames(SC3DEG),OrgDb="org.Hs.eg.db",minGSSize = 5,ont="BP",keyType="SYMBOL")
bp2 <- simplify(DegGOBP,cutoff = 0.7)
dotplot(bp2,showCategory=20)+scale_colour_gradientn(colours = c("red","yellow"))

#Figure 3I
pdf("topDEG.Feature.pdf",width=6,height=9)
FeaturePlot(Tcell,features=c("HSP90AA1","B2M","HSPA1B","JUN","HSPA1A"),pt.size=5,raster=TRUE,split.by="group",cols=c("LightGrey",viridis(10)))&NoLegend()&
theme(axis.text.x = element_blank(),axis.text.y = element_blank(),axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))&
theme(panel.spacing= unit(-1, "lines"),plot.margin = unit(c(0,0,0,0), "lines")) 
dev.off()

#---------------------------Figure 4 generate codes---------------------------------------
#Figure 4 was generated using BcellAnalysis.code.R
Bcell=readRDS("/Projects/deng/Rectal/Bcell/BCell.rds")
#Figure 4A
pdf("BcellType.pdf",height=4,width=5)
TSNEPlot(Bcell, group.by="cellType",label=TRUE)&NoLegend()&theme(axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
#Figure 4B
pdf("BcellsMarker.pdf",width=9)
FeaturePlot(Bcell, c("MS4A1","MZB1","IGHG1","IGHA1"))&theme(axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
#Figure 4C
tmp=paste0(Bcell$orig.ident,"_",Bcell$cellType,sep="")
tmp=as.matrix(table(tmp))
TmpInfo=as.matrix(do.call(rbind, strsplit(as.character(rownames(tmp)),'_')))
result=data.frame("Sample"=TmpInfo[,1],"CellClusters"=TmpInfo[,2],"Percent"=tmp[,1])
Cluster_order=factor(result$CellClusters,levels=c(0:4))
Sample_order=factor(result$Sample,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
cbbPalette <- c("MediumTurquoise", " MediumAquamarine", "Turquoise", "LightSeaGreen", "MediumPurple", "BlueViolet", "Violet", "Magenta")
g=ggplot(result, aes(CellClusters, Percent, fill=Sample_order)) +
  geom_bar(stat="identity",position="fill") +
  scale_y_continuous(expand=c(0,0))+
  scale_fill_manual(values=cbbPalette)+
  theme(axis.text.x = element_text(angle = 0))+
  theme(axis.title.x = element_blank())
pdf("BcellSampleDis.pdf",width=4,height=5)
print(g)
dev.off()

#Figure 4D
geneCombine=read.table("D:/Application/Rectal/Bcell/geneCombine.txt",sep="\t",header=T)
DEGNumber=data.frame(table(geneCombine$subType,geneCombine$Group))
colnames(DEGNumber)=c("SubType","Group","Number")
g=ggplot(DEGNumber, aes(SubType, Number, fill=Group)) +
  geom_bar(stat="identity",position=position_dodge()) +
  scale_y_continuous(expand=c(0,0))+theme_bw()+
  scale_fill_manual(values=c("MediumPurple","Magenta"))+
  theme(axis.text.x = element_text(angle = 0))+
  theme(axis.title.x = element_blank())
pdf("D:/Application/Rectal/Bcell/geneCombineDEGDis.pdf",width=4,height=4)
print(g)
dev.off()


#Figure 4E
IgADEG=geneCombine[geneCombine$subType=="IgA",]
IgAList=split(IgADEG$Symbol,IgADEG$Group)
DegGOBP <- compareCluster(IgAList,fun = "enrichGO",OrgDb="org.Hs.eg.db",keyType="SYMBOL",minGSSize = 5,ont="BP",pvalueCutoff=0.01)
pdf("D:/Application/Rectal/Bcell/geneCombineDEGFunction.pdf",width=6,height=5)
dotplot(DegGOBP,showCategory=8)
dev.off()

#---------------------------Figure 5 generate codes---------------------------------------
#---------------------------Part 3-2 The myelod milieu of Rectal---------------------------------------
setwd("/Projects/deng/Rectal/Graph/Part4")
Myeloid=subset(Rectal,cellType %in% c("Macrophages","Neutrophils","Mast cells"))
Myeloid <- RunPCA(Myeloid, features = VariableFeatures(object = Myeloid),npcs = 100)
Myeloid<- RunTSNE(Myeloid, reduction = "pca", dims = 1:20)
Myeloid<- FindNeighbors(Myeloid, reduction = "pca", dims = 1:20)
Myeloid<- FindClusters(Myeloid, resolution = 0.5)
#Figure 5A
pdf("MyeloidClusterLabel.pdf",height=4,width=5)
TSNEPlot(Myeloid, label=TRUE)&NoLegend()&theme(axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()

#Figure 5B
Myeloid=subset(Myeloid,idents=c(0:4))
tmp=paste0(Myeloid$orig.ident,"_",Myeloid$seurat_clusters,sep="")
tmp=as.matrix(table(tmp))
TmpInfo=as.matrix(do.call(rbind, strsplit(as.character(rownames(tmp)),'_')))
result=data.frame("Sample"=TmpInfo[,1],"CellClusters"=TmpInfo[,2],"Percent"=tmp[,1])
Cluster_order=factor(result$CellClusters,levels=c(0,1,2,4,3))
Sample_order=factor(result$Sample,levels=c("PN1","PN2","SCN1","SCN2","PC1","PC2","SC1","SC2"))
cbbPalette <- c("MediumTurquoise", " MediumAquamarine", "Turquoise", "LightSeaGreen", "MediumPurple", "BlueViolet", "Violet", "Magenta")
g=ggplot(result, aes(Cluster_order, Percent, fill=Sample_order)) +
  geom_bar(stat="identity",position="fill") +
  scale_y_continuous(expand=c(0,0))+
  scale_fill_manual(values=cbbPalette)+
  theme(axis.text.x = element_text(angle = 0))+
  theme(axis.title.x = element_blank(),axis.title.y = element_blank())
pdf("MyeloidSampleDis.pdf",width=5,height=5)
print(g)
dev.off()

#Figure 5C
Idents(Myeloid)=factor(Myeloid$seurat_clusters,levels=c(0,1,2,4,3))
pdf("Marker4Neutrophil.pdf",width=4)
VlnPlot(Myeloid,c("S100A9","S100A8","FCGR3B","G0S2"),ncol=1,pt.size=0)&NoLegend()&theme(plot.title=element_text(size=10),axis.title.x = element_blank(),axis.title.y = element_blank(),axis.text.x = element_blank(),,panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid")) 
dev.off()

#Figure S5A
#--------------------------survive analysis---------------
GeneExprAll=read.table("D:/Application/Rectal/TCGA/TCGA-READ.htseq_fpkm.symbol.txt",header=T,row.names=1,check.names=F)
GeneExpr=GeneExprAll
RectialSurv=read.table("D:/Application/Rectal/TCGA/TCGA-READ.survival.tsv",header=T,row.names=1)
sample=intersect(rownames(RectialSurv),colnames(GeneExpr))
RectialSurv=RectialSurv[sample,]
GeneExpr=t(GeneExpr[,sample])
all(rownames(RectialSurv)==rownames(GeneExpr))
GeneExprSur=data.frame(cbind(RectialSurv,GeneExpr))

GeneExprSur4Tumor <- GeneExprSur[grep(pattern="-01A", rownames(GeneExprSur)), ]

library(survminer)
library(survival)
GeneExprSur4Tumor$Group=ifelse(GeneExprSur4Tumor$G0S2 > quantile(GeneExprSur4Tumor$G0S2,0.5),'high','low')
sfit <- survfit(Surv(OS.time, OS)~Group, data=GeneExprSur4Tumor)
g=ggsurvplot(sfit,conf.int = 'True',pval = T,palette = "Dark2",xlab="Survival Days",legend.title = "G0S2",legend.labs = c("High Expressed", "Low Expressed"))
pdf("D:/Application/Rectal/Manuscript/Graph/Part4/G0S2Sur.pdf",width=5,height=4)
print(g)
dev.off()

GeneExprSur4Tumor$Group=ifelse(GeneExprSur4Tumor$S100A9 > quantile(GeneExprSur4Tumor$S100A9,0.5),'high','low')
sfit <- survfit(Surv(OS.time, OS)~Group, data=GeneExprSur4Tumor)
g=ggsurvplot(sfit,conf.int = 'True',pval = T,palette = "Dark2",xlab="Survival Days",legend.title = "S100A9",legend.labs = c("High Expressed", "Low Expressed"))
pdf("D:/Application/Rectal/Manuscript/Graph/Part4/S100A9Sur.pdf",width=5,height=4)
print(g)
dev.off()

GeneExprSur4Tumor$Group=ifelse(GeneExprSur4Tumor$FCGR3B > quantile(GeneExprSur4Tumor$FCGR3B,0.5),'high','low')
sfit <- survfit(Surv(OS.time, OS)~Group, data=GeneExprSur4Tumor)
g=ggsurvplot(sfit,conf.int = 'True',pval = T,palette = "Dark2",xlab="Survival Days",legend.title = "FCGR3B",legend.labs = c("High Expressed", "Low Expressed"))
pdf("D:/Application/Rectal/Manuscript/Graph/Part4/FCGR3BSur.pdf",width=5,height=4)
print(g)
dev.off()


#---------------------------Figure 6 generate codes---------------------------------------
##############################cell chat#############################################
library(CellChat)
cellchat=readRDS("D:/Application/Rectal/CellChat/cellchat_Rectal8MyCellChatDB.rds")
cellchat@idents=factor(cellchat@idents,levels=c(paste0("EPC_",c(0,10,13,3,17,2,8,6,11,16,15,1,7,12,14,9,4,5)),paste0("Tcell_",c(0:15)),"Macrophages","Neutrophils","Mast cells"))

groupSize <- as.numeric(table(cellchat@idents))
pdf("netVisual_circle.pdf",width=8,height=8.5)
netVisual_circle(cellchat@net$count,vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
dev.off()

pdf("netVisual_circle4Neutrophils.pdf",width=8,height=8.5)
netVisual_circle(cellchat@net$weight,vertex.weight = groupSize,sources.use = "Neutrophils", weight.scale = T, label.edge= F)
dev.off()

netVisual_bubble(cellchat, targets.use = paste0("Tcell_",c(0:15)),  sources.use = c("Neutrophils"), remove.isolate = FALSE)
netVisual_bubble(cellchat, sources.use = paste0("Tcell_",c(0:15)),  targets.use = c("Neutrophils"), remove.isolate = FALSE)

netVisual_bubble(cellchat, sources.use = paste0("Tcell_",c(0:5)),  targets.use = paste0("EPC_",c(0,10,13,3,17,2,8,6,11,16,15,1,7,12,14,9,4,5)), remove.isolate = FALSE)
netVisual_bubble(cellchat, targets.use = paste0("Tcell_",c(0:5)),  sources.use = paste0("EPC_",c(0,10,13,3,17,2,8,6,11,16,15,1,7,12,14,9,4,5)), remove.isolate = FALSE)

netVisual_bubble(cellchat, sources.use = paste0("EPC_",c(0:17)),  targets.use = c("Neutrophils"), remove.isolate = FALSE)


pdf("cellChatRecptor.pdf")
FeaturePlot(Myeloid, c("CXCR4","PTPRC","CD44","CXCR2"))&theme(axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()
pdf("cellChatSource.pdf")
FeaturePlot(Myeloid, c("B2M","HLA-B","S100A9","MIF"))&theme(axis.title.x = element_blank(),axis.title.y = element_blank(),panel.border = element_rect(fill=NA,color="black", size=1.5, linetype="solid"))
dev.off()